### ISSUE TITLE
My permanent scratch ban / statements

### ISSUE THREAD

**Issue by AfterNetwork** [AfterNetwork/AFNNetworkK12-Creations#14]
I am officially permanently banned from scratch for an IP grabber scenario. The scenario became very dramatic resulting in the ST banning me forever. In the meantime, I've been working on RBLX development. 

A statement to the people who were affected by this:
Ello scratchers, If you are reading this you were affected by something I did 3 months ago. I used an IP grabber to just startle people as a joke. I have learned my lesson and I am deeply sorry if this affected you. I explained the joke to everyone right after which everyone was (mostly) fine with. I never said sorry though. One person was really mad and reported me to Scratch for this. I got banned forever sadly after that. I am very sorry and I will not do this behaviour again. Sorry for the issue.

A statement to the forums:
Ello forumers, I acted pretty childish after the IP grabber situation (as described above) on the forums. I used the forums to spread even more drama, which was wrong of me. I may startled some of you, and I'm sorry. I didn't have any malicious intent using these IPs. I just wanted to do a quick joke for fun and thats it. I thought it would be funny to do this, but I understand now that this is serious and I should not do this again nor try to cause drama about. I've learned my lesson and I'm sorry.

A statement to the Scratch Team:
Ello ST, I understand the scenario I created the IP grabber was wrongful and I am sorry for what happened. It's been 3 months and I've thinking about my choices and I just realized I may have startled some people. I though this was funny, but this is a serious situation and I should have probably not have done this nor spread drama about it. I am seriously deeply sorry about the situation and I will not do it again because I realized my mistakes and I have learned for them.
 
Thank you,
AFNNetworkK12

---------------------------------------------------------------------------------------------------------------
These 3 statements to the people and the administrators are my words to everyone because I want to be sorry, I'm okay if I don't get unbanned, but I just want to have that fun again. The statement to the ST will be used in my third appeal to the ST.

Sincerely,
AFNNetworkK12

**Comment by VelocityDesign** [comment]
@llk

**Comment by AfterNetwork** [comment]
erm..

**Comment by AfterNetwork** [comment]
thats their development team not their moderation/appeals team

**Comment by Semisol** [comment]
^

**Comment by VelocityDesign** [comment]
Oh, yeah. @mention Paddle2See

**Comment by AlphaZetta** [comment]
> I am officially permanently banned from scratch for an IP grabber scenario. The scenario became very dramatic resulting in the ST banning me forever. In the meantime, I've been working on RBLX development.
> 
> A statement to the people who were affected by this:
> Ello scratchers, If you are reading this you were affected by something I did 3 months ago. I used an IP grabber to just startle people as a joke. I have learned my lesson and I am deeply sorry if this affected you. I explained the joke to everyone right after which everyone was (mostly) fine with. I never said sorry though. One person was really mad and reported me to Scratch for this. I got banned forever sadly after that. I am very sorry and I will not do this behaviour again. Sorry for the issue.
> 
> A statement to the forums:
> Ello forumers, I acted pretty childish after the IP grabber situation (as described above) on the forums. I used the forums to spread even more drama, which was wrong of me. I may startled some of you, and I'm sorry. I didn't have any malicious intent using these IPs. I just wanted to do a quick joke for fun and thats it. I thought it would be funny to do this, but I understand now that this is serious and I should not do this again nor try to cause drama about. I've learned my lesson and I'm sorry.
> 
> A statement to the Scratch Team:
> Ello ST, I understand the scenario I created the IP grabber was wrongful and I am sorry for what happened. It's been 3 months and I've thinking about my choices and I just realized I may have startled some people. I though this was funny, but this is a serious situation and I should have probably not have done this nor spread drama about it. I am seriously deeply sorry about the situation and I will not do it again because I realized my mistakes and I have learned for them.
> 
> Thank you,
> AFNNetworkK12
> 
> These 3 statements to the people and the administrators are my words to everyone because I want to be sorry, I'm okay if I don't get unbanned, but I just want to have that fun again. The statement to the ST will be used in my third appeal to the ST.
> 
> Sincerely,
> AFNNetworkK12

lmao you  got what you deserved.
You abused me in ShopBux.
You abused the currency in ShopBux.
You manipulated everyone in ShopBux.
You are the most toxic person I know.
I hope I never speak to you again.

**Comment by NYCDOT1** [comment]
AFN, committing crimes since 2008.

**Comment by ajsya** [comment]
I was linked this by someone and I would just like to say the following, rip

**Comment by AfterNetwork** [comment]
> > I am officially permanently banned from scratch for an IP grabber scenario. The scenario became very dramatic resulting in the ST banning me forever. In the meantime, I've been working on RBLX development.
> > A statement to the people who were affected by this:
> > Ello scratchers, If you are reading this you were affected by something I did 3 months ago. I used an IP grabber to just startle people as a joke. I have learned my lesson and I am deeply sorry if this affected you. I explained the joke to everyone right after which everyone was (mostly) fine with. I never said sorry though. One person was really mad and reported me to Scratch for this. I got banned forever sadly after that. I am very sorry and I will not do this behaviour again. Sorry for the issue.
> > A statement to the forums:
> > Ello forumers, I acted pretty childish after the IP grabber situation (as described above) on the forums. I used the forums to spread even more drama, which was wrong of me. I may startled some of you, and I'm sorry. I didn't have any malicious intent using these IPs. I just wanted to do a quick joke for fun and thats it. I thought it would be funny to do this, but I understand now that this is serious and I should not do this again nor try to cause drama about. I've learned my lesson and I'm sorry.
> > A statement to the Scratch Team:
> > Ello ST, I understand the scenario I created the IP grabber was wrongful and I am sorry for what happened. It's been 3 months and I've thinking about my choices and I just realized I may have startled some people. I though this was funny, but this is a serious situation and I should have probably not have done this nor spread drama about it. I am seriously deeply sorry about the situation and I will not do it again because I realized my mistakes and I have learned for them.
> > Thank you,
> > AFNNetworkK12
> > These 3 statements to the people and the administrators are my words to everyone because I want to be sorry, I'm okay if I don't get unbanned, but I just want to have that fun again. The statement to the ST will be used in my third appeal to the ST.
> > Sincerely,
> > AFNNetworkK12
> 
> lmao you got what you deserved.
> You abused me in ShopBux.
> You abused the currency in ShopBux.
> You manipulated everyone in ShopBux.
> You are the most toxic person I know.
> I hope I never speak to you again.

I honestly have to say this, but:
I'm sorry for all the trouble I've ever done in SSB. I just get frustrated easily and I can get toxic quick. I might have found ways to abuse the currency, but now I know it is wrong to do this. I manipulated everyone and I am deeply sorry for that. I thought that this entire thing was just a game that I controlled. Turns out I don't control the currency. I wanted to have fun but I ruined that chance forever when I caused multiple incidents. Now I realize that SSB is a democratic republic. MCLovers has power over everyone else, but other than that, it's a democracy. All these situations were crazy. I didn't know what I was thinking abusing shopbux to the edge of my mind. It's like I was a person who didn't really care about anyone in the past. Now I just sit here thinking about those devastating moments and how I could improve. I am deeply sorry for any damage I have ever done to SSB. I would like to say this to finalize things and close any drama/situations and say sorry to the entire Scratch community. I just wanted to have fun, but I had fun in the wrong way. Thank you for reading this.

Best regards,
After
----------------------------------------------------------
@Semisol @AlphaZetta @ajsya @NYCDOT1 
Please read.

**Comment by AfterNetwork** [comment]
> AFN, committing crimes since 2008.

If you are joking over this, I have to say that is a professional apology and statement to the scratch community about all the drama I have caused and the situation that has gotten me banned. Anyways, I am sorry for any drama and crime I have caused as described above. Thank you.

**Comment by AlphaZetta** [comment]
> > > I am officially permanently banned from scratch for an IP grabber scenario. The scenario became very dramatic resulting in the ST banning me forever. In the meantime, I've been working on RBLX development.
> > > A statement to the people who were affected by this:
> > > Ello scratchers, If you are reading this you were affected by something I did 3 months ago. I used an IP grabber to just startle people as a joke. I have learned my lesson and I am deeply sorry if this affected you. I explained the joke to everyone right after which everyone was (mostly) fine with. I never said sorry though. One person was really mad and reported me to Scratch for this. I got banned forever sadly after that. I am very sorry and I will not do this behaviour again. Sorry for the issue.
> > > A statement to the forums:
> > > Ello forumers, I acted pretty childish after the IP grabber situation (as described above) on the forums. I used the forums to spread even more drama, which was wrong of me. I may startled some of you, and I'm sorry. I didn't have any malicious intent using these IPs. I just wanted to do a quick joke for fun and thats it. I thought it would be funny to do this, but I understand now that this is serious and I should not do this again nor try to cause drama about. I've learned my lesson and I'm sorry.
> > > A statement to the Scratch Team:
> > > Ello ST, I understand the scenario I created the IP grabber was wrongful and I am sorry for what happened. It's been 3 months and I've thinking about my choices and I just realized I may have startled some people. I though this was funny, but this is a serious situation and I should have probably not have done this nor spread drama about it. I am seriously deeply sorry about the situation and I will not do it again because I realized my mistakes and I have learned for them.
> > > Thank you,
> > > AFNNetworkK12
> > > These 3 statements to the people and the administrators are my words to everyone because I want to be sorry, I'm okay if I don't get unbanned, but I just want to have that fun again. The statement to the ST will be used in my third appeal to the ST.
> > > Sincerely,
> > > AFNNetworkK12
> > 
> > 
> > lmao you got what you deserved.
> > You abused me in ShopBux.
> > You abused the currency in ShopBux.
> > You manipulated everyone in ShopBux.
> > You are the most toxic person I know.
> > I hope I never speak to you again.
> 
> I honestly have to say this, but:
> I'm sorry for all the trouble I've ever done in SSB. I just get frustrated easily and I can get toxic quick. I might have found ways to abuse the currency, but now I know it is wrong to do this. I manipulated everyone and I am deeply sorry for that. I thought that this entire thing was just a game that I controlled. Turns out I don't control the currency. I wanted to have fun but I ruined that chance forever when I caused multiple incidents. Now I realize that SSB is a democratic republic. MCLovers has power over everyone else, but other than that, it's a democracy. All these situations were crazy. I didn't know what I was thinking abusing shopbux to the edge of my mind. It's like I was a person who didn't really care about anyone in the past. Now I just sit here thinking about those devastating moments and how I could improve. I am deeply sorry for any damage I have ever done to SSB. I would like to say this to finalize things and close any drama/situations and say sorry to the entire Scratch community. I just wanted to have fun, but I had fun in the wrong way. Thank you for reading this.
> 
> Best regards,
> 
> ## After
> @Semisol @AlphaZetta @ajsya @NYCDOT1
> Please read.

I have not forgiven you.
I do not forgive you.
And I will not forgive you.
You are a master manipulator. You are the thing I would see in my nightmares. You don't know how many nights I went to sleep, stressed that my whole organization would turn on me. If you murdered someone, would apologising make it better? No. I pity the people who you meet in the future. The people you befriend, date. They would have to go through exactly what I did but 100 times worse. You're a child. A rude one. A disgusting one. And an idiotic one. You are not sorry. You will never be sorry. You said the same thing to ShopBux last time. What makes this time different? We're not on Scratch anymore, the guidelines don't apply. So, AfterNetwork. Fuck you.

**Comment by AlphaZetta** [comment]
No one legitimately likes you. The people you trust the most on the internet have told me the truth about how they feel. I hope you know that. You deserve every negative consequence. You deserve it all. I hate you more than words can express. Yes, even more than the homophobe @VelocityDesign . I hate you more than them all. Please save everyone you know and leave. Leave Github. Leave Social Media. Leave the internet. I gave you chance after chance after chance! You betrayed them all! Fuck you AfterNetwork. Fuck you.

**Comment by AlphaZetta** [comment]
k maybe not more than the homophobe but you still suck

**Comment by AfterNetwork** [comment]
> No one legitimately likes you. The people you trust the most on the internet have told me the truth about how they feel. I hope you know that. You deserve every negative consequence. You deserve it all. I hate you more than words can express. Yes, even more than the homophobe @VelocityDesign . I hate you more than them all. Please save everyone you know and leave. Leave Github. Leave Social Media. Leave the internet. I gave you chance after chance after chance! You betrayed them all! Fuck you AfterNetwork. Fuck you.

Woah. You put in a full in argument. Let’s just cool down the discussion.

> No one legitimately likes you.
I mean, I’m an introvert so I’m honestly just used to being alone. Same thing in real life, because I like to keep silent and just get ideas.

> The people you trust the most on the internet have told me the truth about how they feel. I hope you know that. You deserve every negative consequence. You deserve it all.
I care about how they feel and I take their feedback. I don’t want to be the idiot I was half a year that haunts me. I want to be a better person and clear my name about every bad thing I’ve done. I’m not the same person I was half a year ago. I’ve learned my lesson throughout the time of my ban.

> I hate you more than them all. Please save everyone you know and leave.
That’s harsh, but I need some people to socialize with to keep my sanity.

> Leave github. Leave the internet.
Here’s the thing: I think the internet has changed me overtime from an idiot to a nicer person. I learned to socialize with people and do stuff with them. I honestly think that the internet is the place for me.

> I gave you chance after chance!
The thing is: this was when I had no sense of feelings towards others and listening to them. I just didn’t want to listen to you back then, but now I realize that you stabilize your own little part and I should accept that chance and change. I now know that, but the past still haunts me.

> You betrayed them all!
I was an idiot to do this. I just wanted power, but now I realize that everyone needs a piece of power and I already had one. It’s sad of how I did this back then.

> Fuck you Afternetwork. Fuck you!
That’s harsh, but I’m actually sorry for what I have done. I don’t want to be a careless idiot. I want to be a person on the internet who actually takes feedback and cares for people. The point is: I’ve changed over time.
Thanks for reading.

Regards,

After

**Comment by AfterNetwork** [comment]
@AlphaZetta One more additional thing: now I understand that you don't trust me because I broke your trust many times. I was an idiot not to take the chances

**Comment by AlphaZetta** [comment]
And blocked!

**Comment by ajsya** [comment]
Drama over a dead forum topic? I wish you your best AfterNetwork.

**Comment by AfterNetwork** [comment]
closed, do not talk because drama
