### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by AfterNetwork** [AfterNetwork/AFNNetworkK12-Creations#7]
I'm working on a python script, but I don't really know python.

**Comment by Nambaseking01** [comment]
`print("Hello World")`

pretty much all I know ;-;

**Comment by jbrow78** [comment]
Lol, I know ruby. There is an easy gem to convert your scripts to python...

**Comment by AfterNetwork** [comment]
> Lol, I know ruby. There is an easy gem to convert your scripts to python...

JS is my native language, so consider this closed.
